import type { MoveVfxRecipe } from './types'
import type { MoveVfxAssetId } from './vfxManifest'

export const MOVE_VFX_RECIPES = {
  neutralBeam: {
    id: 'neutral-beam',
    label: 'Neutral thrust + focused spark',
    durationMs: 820,
    impactAtMs: 430,
    steps: [
      {
        id: 'thrust',
        assetId: 'thrust',
        startAtMs: 0,
        durationMs: 560,
        motion: 'projectile',
      },
      {
        id: 'focus-ring',
        assetId: 'kenneyMagic',
        startAtMs: 120,
        durationMs: 430,
        anchor: 'attacker',
        scaleMultiplier: 0.46,
        opacity: 0.52,
      },
      {
        id: 'impact-spark',
        assetId: 'kenneySpark',
        startAtMs: 400,
        durationMs: 420,
        anchor: 'target',
        scaleMultiplier: 0.55,
        opacity: 0.74,
      },
    ],
  },

  slashImpact: {
    id: 'slash-impact',
    label: 'Slash + arc + spark',
    durationMs: 720,
    impactAtMs: 300,
    steps: [
      {
        id: 'base-slash',
        assetId: 'slash',
        startAtMs: 0,
        durationMs: 520,
        anchor: 'target',
      },
      {
        id: 'clean-arc',
        assetId: 'kenneySlash',
        startAtMs: 90,
        durationMs: 430,
        anchor: 'target',
        scaleMultiplier: 1.12,
        opacity: 0.88,
      },
      {
        id: 'impact-spark',
        assetId: 'kenneySpark',
        startAtMs: 270,
        durationMs: 390,
        anchor: 'target',
        scaleMultiplier: 0.46,
        opacity: 0.66,
      },
    ],
  },

  bluntImpact: {
    id: 'blunt-impact',
    label: 'Punch + spark + dust',
    durationMs: 760,
    impactAtMs: 300,
    steps: [
      {
        id: 'base-punch',
        assetId: 'punch',
        startAtMs: 0,
        durationMs: 520,
        anchor: 'target',
      },
      {
        id: 'impact-spark',
        assetId: 'kenneySpark',
        startAtMs: 270,
        durationMs: 390,
        anchor: 'target',
        scaleMultiplier: 0.52,
        opacity: 0.76,
      },
      {
        id: 'dust',
        assetId: 'kenneySmoke',
        startAtMs: 300,
        durationMs: 460,
        anchor: 'target',
        scaleMultiplier: 0.54,
        opacity: 0.34,
      },
    ],
  },

  heavyImpact: {
    id: 'heavy-impact',
    label: 'Guard break + heavy dust',
    durationMs: 1420,
    impactAtMs: 500,
    steps: [
      {
        id: 'break',
        assetId: 'guardBreakGif',
        startAtMs: 0,
        durationMs: 1180,
        anchor: 'target',
      },
      {
        id: 'impact-spark',
        assetId: 'kenneySpark',
        startAtMs: 450,
        durationMs: 460,
        anchor: 'target',
        scaleMultiplier: 0.72,
        opacity: 0.82,
      },
      {
        id: 'heavy-dust',
        assetId: 'kenneySmoke',
        startAtMs: 500,
        durationMs: 720,
        anchor: 'target',
        scaleMultiplier: 0.82,
        opacity: 0.5,
      },
    ],
  },

  natureShimmer: {
    id: 'nature-shimmer',
    label: 'Nature shimmer + magic focus',
    durationMs: 1120,
    impactAtMs: 420,
    steps: [
      {
        id: 'shimmer',
        assetId: 'shimmer',
        startAtMs: 0,
        durationMs: 1000,
        anchor: 'target',
      },
      {
        id: 'magic-focus',
        assetId: 'kenneyMagic',
        startAtMs: 180,
        durationMs: 620,
        anchor: 'target',
        scaleMultiplier: 0.66,
        opacity: 0.58,
      },
    ],
  },

  firePulseImpact: {
    id: 'fire-pulse-impact',
    label: 'Fire pulse + smoke impact',
    durationMs: 1040,
    impactAtMs: 430,
    steps: [
      {
        id: 'fire-pulse',
        assetId: 'firePulseGif',
        startAtMs: 0,
        durationMs: 880,
        anchor: 'target',
      },
      {
        id: 'hot-smoke',
        assetId: 'kenneySmoke',
        startAtMs: 390,
        durationMs: 620,
        anchor: 'target',
        scaleMultiplier: 0.58,
        opacity: 0.38,
      },
      {
        id: 'impact-spark',
        assetId: 'kenneySpark',
        startAtMs: 410,
        durationMs: 410,
        anchor: 'target',
        scaleMultiplier: 0.4,
        opacity: 0.58,
      },
    ],
  },

  fireProjectile: {
    id: 'fire-projectile',
    label: 'Fire projectile + impact',
    durationMs: 1160,
    impactAtMs: 560,
    steps: [
      {
        id: 'projectile',
        assetId: 'fireballGif',
        startAtMs: 0,
        durationMs: 700,
        motion: 'projectile',
      },
      {
        id: 'impact',
        assetId: 'fireImpactGif',
        startAtMs: 500,
        durationMs: 660,
        anchor: 'target',
        motion: 'static',
        scaleMultiplier: 1.08,
      },
      {
        id: 'impact-smoke',
        assetId: 'kenneySmoke',
        startAtMs: 540,
        durationMs: 600,
        anchor: 'target',
        scaleMultiplier: 0.6,
        opacity: 0.38,
      },
    ],
  },

  electricBolt: {
    id: 'electric-bolt',
    label: 'Electric projectile + lightning impact',
    durationMs: 1080,
    impactAtMs: 410,
    steps: [
      {
        id: 'charge-projectile',
        assetId: 'energyGif',
        startAtMs: 0,
        durationMs: 500,
        motion: 'projectile',
        scaleMultiplier: 0.9,
      },
      {
        id: 'lightning-impact',
        assetId: 'lightningGif',
        startAtMs: 350,
        durationMs: 730,
        anchor: 'target',
        motion: 'static',
        scaleMultiplier: 1.08,
      },
      {
        id: 'electric-spark',
        assetId: 'kenneySpark',
        startAtMs: 370,
        durationMs: 500,
        anchor: 'target',
        scaleMultiplier: 0.7,
        opacity: 0.82,
      },
    ],
  },

  waterJet: {
    id: 'water-jet',
    label: 'Water projectile + splash',
    durationMs: 1500,
    impactAtMs: 720,
    steps: [
      {
        id: 'water-projectile',
        assetId: 'waterGif',
        startAtMs: 0,
        durationMs: 900,
        motion: 'projectile',
        scaleMultiplier: 0.92,
      },
      {
        id: 'water-splash',
        assetId: 'waterTorrentGif',
        startAtMs: 650,
        durationMs: 850,
        anchor: 'target',
        motion: 'static',
        scaleMultiplier: 0.58,
      },
      {
        id: 'splash-ring',
        assetId: 'kenneyMagic',
        startAtMs: 690,
        durationMs: 470,
        anchor: 'target',
        scaleMultiplier: 0.5,
        opacity: 0.34,
      },
    ],
  },

  psychicBurst: {
    id: 'psychic-burst',
    label: 'Psychic focus + burst',
    durationMs: 1450,
    impactAtMs: 600,
    steps: [
      {
        id: 'psychic-focus',
        assetId: 'psychicGif',
        startAtMs: 0,
        durationMs: 900,
        anchor: 'target',
      },
      {
        id: 'psychic-ring',
        assetId: 'kenneyMagic',
        startAtMs: 300,
        durationMs: 720,
        anchor: 'target',
        scaleMultiplier: 0.76,
        opacity: 0.72,
      },
      {
        id: 'psychic-impact',
        assetId: 'psychicBurstGif',
        startAtMs: 480,
        durationMs: 970,
        anchor: 'target',
        scaleMultiplier: 0.9,
      },
    ],
  },

  healingPulse: {
    id: 'healing-pulse',
    label: 'Healing + shimmer',
    durationMs: 1500,
    impactAtMs: 0,
    steps: [
      {
        id: 'healing',
        assetId: 'cureGif',
        startAtMs: 0,
        durationMs: 1400,
        anchor: 'self',
      },
      {
        id: 'healing-ring',
        assetId: 'kenneyMagic',
        startAtMs: 40,
        durationMs: 780,
        anchor: 'self',
        scaleMultiplier: 0.72,
        opacity: 0.68,
      },
      {
        id: 'shimmer',
        assetId: 'shimmer',
        startAtMs: 180,
        durationMs: 900,
        anchor: 'self',
        scaleMultiplier: 0.72,
        opacity: 0.82,
      },
    ],
  },
} satisfies Record<string, MoveVfxRecipe>

export type MoveVfxRecipeId = keyof typeof MOVE_VFX_RECIPES

export const MOVE_VFX_RECIPE_BY_PRIMARY_ASSET: Partial<
  Record<MoveVfxAssetId, MoveVfxRecipeId>
> = {
  thrust: 'neutralBeam',
  slash: 'slashImpact',
  punch: 'bluntImpact',
  guardBreakGif: 'heavyImpact',
  shimmer: 'natureShimmer',
  firePulseGif: 'firePulseImpact',
  fireballGif: 'fireProjectile',
  energyGif: 'electricBolt',
  lightningGif: 'electricBolt',
  waterGif: 'waterJet',
  waterTorrentGif: 'waterJet',
  psychicGif: 'psychicBurst',
  psychicBurstGif: 'psychicBurst',
  cure: 'healingPulse',
  cureGif: 'healingPulse',
}
