import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { readFile } from 'node:fs/promises'

async function tools(page: Page, tab: string) {
  await page.getByRole('button', { name: 'Partita', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'La tua partita' })
  await dialog.getByRole('button', { name: tab, exact: true }).click()
  return dialog
}
test('preferences persist independently and dialog is keyboard accessible', async ({ page }) => {
  await page.goto('/')
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message))
  const dialog = await tools(page, 'Impostazioni')
  await dialog.getByLabel('Velocità animazioni').selectOption('fast')
  await dialog.getByLabel('Movimento ridotto').selectOption('on')
  await dialog.getByRole('slider', { name: 'Volume musica' }).fill('25')
  await dialog.getByRole('slider', { name: 'Volume effetti' }).fill('70')
  const a11y = await new AxeBuilder({ page }).include('[data-game-dialog]').analyze()
  expect(a11y.violations).toEqual([])
  await test.info().attach('Impostazioni della partita', { body: await page.screenshot(), contentType: 'image/png' })
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Partita', exact: true })).toBeFocused()
  await page.reload()
  const reopened = await tools(page, 'Impostazioni')
  await expect(reopened.getByLabel('Velocità animazioni')).toHaveValue('fast')
  await expect(reopened.getByRole('slider', { name: 'Volume musica' })).toHaveValue('25')
  await expect(reopened.getByRole('slider', { name: 'Volume effetti' })).toHaveValue('70')
  await expect(reopened.getByLabel('Movimento ridotto')).toHaveValue('on')
  expect(errors).toEqual([])
})

test('new campaign chooses two starters and survives reload', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Nuova Partita', exact: true }).click()
  await expect(page.locator('[data-presented-scene="laboratorio"]')).toHaveAttribute('aria-busy', 'false')
  await page.getByLabel('Giocatore 1', { exact: true }).fill('E2E Uno')
  await page.getByLabel('Giocatore 2', { exact: true }).fill('E2E Due')
  await page.getByRole('button', { name: 'Continua', exact: true }).click()
  await page.getByRole('button', { name: /Vyrath/ }).click()
  await page.getByRole('button', { name: /Darklaw/ }).click()
  await expect(page.locator('[data-presented-scene="mappa-principale"]')).toHaveAttribute('aria-busy', 'false')
  await page.reload()
  await expect(page.locator('[data-presented-scene="mappa-principale"]')).toHaveAttribute('aria-busy', 'false')
  const data = await page.evaluate(() => JSON.parse(localStorage.getItem('arkamon-save') || '{}'))
  // Test the persisted game contract rather than loading a second Vite store instance.
  expect(data.state.giocatore1.squadra[0].specieId).toBe(1)
  expect(data.state.giocatore2.squadra[0].specieId).toBe(5)
})

test('backup export, preview, cancellation and confirmed restore preserve the campaign', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Nuova Partita', exact: true }).click()
  await expect(page.locator('[data-presented-scene="laboratorio"]')).toHaveAttribute('aria-busy', 'false')
  await page.getByLabel('Giocatore 1', { exact: true }).fill('Backup Uno')
  await page.getByLabel('Giocatore 2', { exact: true }).fill('Backup Due')
  await page.getByRole('button', { name: 'Continua', exact: true }).click()
  await page.getByRole('button', { name: /Vyrath/ }).click()
  await page.getByRole('button', { name: /Darklaw/ }).click()
  await expect(page.locator('[data-presented-scene="mappa-principale"]')).toHaveAttribute('aria-busy', 'false')
  const before = await page.evaluate(() => localStorage.getItem('arkamon-save'))
  const dialog = await tools(page, 'Backup')
  const downloadPromise = page.waitForEvent('download')
  await dialog.getByRole('button', { name: 'Scarica backup partita', exact: true }).click()
  const download = await downloadPromise
  const text = await readFile((await download.path())!, 'utf8')
  const saved = JSON.parse(text)
  expect(saved.version).toBe(1)
  expect(saved.campaign.giocatore1.squadra[0].hp).toBeGreaterThan(0)
  await dialog.getByLabel('Importa backup partita').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"hello":"world"}') })
  await expect(dialog.getByRole('alert')).toContainText('non è un backup')
  expect(await page.evaluate(() => localStorage.getItem('arkamon-save'))).toBe(before)
  await dialog.getByLabel('Importa backup partita').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: Buffer.from(text) })
  await expect(dialog.getByLabel('Anteprima ripristino')).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Ripristina questa partita' })).toBeDisabled()
  await dialog.getByRole('button', { name: 'Annulla importazione' }).click()
  expect(await page.evaluate(() => localStorage.getItem('arkamon-save'))).toBe(before)
  saved.campaign.giocatore1.nome = 'Ripristinato'
  saved.campaign.giocatore1.squadra[0].hp = 3
  await dialog.getByLabel('Importa backup partita').setInputFiles({ name: 'updated.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(saved)) })
  await dialog.getByRole('checkbox', { name: /Confermo la sostituzione/ }).check()
  await dialog.getByRole('button', { name: 'Ripristina questa partita' }).click()
  await expect(dialog.getByRole('status')).toContainText('Partita ripristinata')
  await expect(dialog.getByRole('button', { name: 'Scarica backup precedente' })).toBeVisible()
  await page.keyboard.press('Escape'); await page.reload()
  const restored = await page.evaluate(() => JSON.parse(localStorage.getItem('arkamon-save') || '{}').state)
  expect(restored.giocatore1.nome).toBe('Ripristinato')
  expect(restored.giocatore1.squadra[0].hp).toBe(3)
  expect(restored.giocatore2.squadra[0].specieId).toBe(5)
})

test('interaction editor persists definitions and journal shows per-player requirements', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Admin', exact: true }).click()
  await page.getByRole('button', { name: 'Interazioni', exact: true }).click()
  const editor = page.getByRole('region', { name: 'Editor delle interazioni' })
  await editor.getByLabel('Titolo', { exact: true }).fill('Indizio di prova')
  await editor.getByLabel('Dialogo o istruzioni').fill('Esamina il diario e raggiungi il ponte.')
  await editor.getByLabel('Livello minimo in squadra').fill('10')
  await editor.getByRole('button', { name: 'Salva interazione', exact: true }).click()
  await expect(editor.getByRole('status')).toHaveText('Interazione salvata.')
  await page.getByRole('button', { name: 'Chiudi', exact: true }).click()
  const journal = await tools(page, 'Diario')
  await expect(journal).toContainText('Indizio di prova')
  await expect(journal).toContainText('progressi individuali')
  await journal.getByLabel('Giocatore del diario').selectOption('2')
  await expect(journal).toContainText('Indizio di prova')
  await page.keyboard.press('Escape'); await page.reload()
  await page.getByRole('button', { name: 'Admin', exact: true }).click()
  await page.getByRole('button', { name: 'Interazioni', exact: true }).click()
  const savedOption = await page.getByLabel('Interazione esistente').locator('option').filter({ hasText: 'Indizio di prova' }).getAttribute('value')
  await page.getByLabel('Interazione esistente').selectOption(savedOption!)
  await expect(page.getByLabel('Titolo', { exact: true })).toHaveValue('Indizio di prova')
  const a11y = await new AxeBuilder({ page }).include('.interaction-editor').analyze()
  expect(a11y.violations).toEqual([])
  await test.info().attach('Editor delle interazioni', { body: await page.screenshot(), contentType: 'image/png' })
})

test('a configured interaction pays once, ends the turn and preserves separate player progress', async ({ page }) => {
  await page.goto('/')
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message))
  await page.getByRole('button', { name: 'Nuova Partita', exact: true }).click()
  await expect(page.locator('[data-presented-scene="laboratorio"]')).toHaveAttribute('aria-busy', 'false')
  await page.getByRole('button', { name: 'Continua', exact: true }).click()
  await page.getByRole('button', { name: /Vyrath/ }).click()
  await page.getByRole('button', { name: /Darklaw/ }).click()
  await expect(page.locator('[data-presented-scene="mappa-principale"]')).toHaveAttribute('aria-busy', 'false')
  await page.getByRole('button', { name: 'Admin', exact: true }).click()
  await page.getByRole('button', { name: 'Interazioni', exact: true }).click()
  const editor = page.getByRole('region', { name: 'Editor delle interazioni' })
  await editor.getByLabel('Titolo', { exact: true }).fill('Messaggio del ponte')
  await editor.getByLabel('Dialogo o istruzioni').fill('Hai trovato il primo indizio.')
  await editor.getByLabel('Monete da assegnare').fill('50')
  await editor.getByRole('button', { name: 'Salva interazione', exact: true }).click()
  await expect(editor.getByRole('status')).toHaveText('Interazione salvata.')
  await page.getByRole('button', { name: 'Chiudi', exact: true }).click()
  // Locate both players at this defined point without spending gameplay actions to reach it.
  const definition = await page.evaluate(() => {
    const catalog = JSON.parse(localStorage.getItem('arkamon-interactions-v1')!).state.interactions
    const entry = catalog[0]
    const saved = JSON.parse(localStorage.getItem('arkamon-save')!)
    saved.state.posizione1.luogo = entry.mapId; saved.state.posizione2.luogo = entry.mapId
    saved.state.posizioniLocali1 = { [entry.mapId]: entry.nodeId }
    saved.state.posizioniLocali2 = { [entry.mapId]: entry.nodeId }
    saved.state.scenaCorrente = { scena: 'citta', payload: { luogo: entry.mapId } }
    saved.state.giocatore1.monete = 100; saved.state.giocatore2.monete = 100
    localStorage.setItem('arkamon-save', JSON.stringify(saved))
    return entry
  })
  await page.reload()
  const scene = page.locator('[data-presented-scene="citta:Venezia"]')
  await expect(scene).toHaveAttribute('aria-busy', 'false')
  await scene.getByRole('button', { name: 'Interagisci sul punto', exact: true }).click()
  let interaction = page.getByRole('dialog', { name: 'Interazioni del punto' })
  await interaction.getByRole('button', { name: 'Interagisci', exact: true }).click()
  await expect(interaction.getByRole('button', { name: 'Completata', exact: true })).toBeDisabled()
  const completed = await page.evaluate(() => JSON.parse(localStorage.getItem('arkamon-save')!).state)
  expect(completed.giocatore1.monete).toBe(150)
  expect(completed.giocatore2.monete).toBe(100)
  expect(completed.interactionProgress.completed1).toEqual([definition.id])
  expect(completed.interactionProgress.completed2).toEqual([])
  expect(completed.turnoOverworld).toEqual({ giocatoreAttivo: 2, azioniRimaste: 2 })
  await page.keyboard.press('Escape'); await page.reload()
  await expect(scene).toHaveAttribute('aria-busy', 'false')
  await scene.getByRole('button', { name: 'Interagisci sul punto', exact: true }).click()
  interaction = page.getByRole('dialog', { name: 'Interazioni del punto' })
  await expect(interaction.getByRole('button', { name: 'Completata', exact: true })).toBeDisabled()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('arkamon-save')!).state.giocatore1.monete)).toBe(150)
  const a11y = await new AxeBuilder({ page }).include('.local-map-activities:not([hidden])').analyze()
  expect(a11y.violations).toEqual([])
  await test.info().attach('Interazione completata sulla mappa', { body: await page.screenshot(), contentType: 'image/png' })
  await page.keyboard.press('Escape')
  await scene.getByRole('button', { name: 'Passa turno', exact: true }).click()
  await scene.getByRole('button', { name: 'Interagisci sul punto', exact: true }).click()
  await page.getByRole('dialog', { name: 'Interazioni del punto' }).getByRole('button', { name: 'Interagisci', exact: true }).click()
  const both = await page.evaluate(() => JSON.parse(localStorage.getItem('arkamon-save')!).state)
  expect(both.giocatore1.monete).toBe(150); expect(both.giocatore2.monete).toBe(150)
  expect(both.interactionProgress.completed1).toEqual([definition.id])
  expect(both.interactionProgress.completed2).toEqual([definition.id])
  expect(errors).toEqual([])
})
