import type { AdminTheme } from './adminThemeTypes'
import {
  defaultAdminTheme,
  defaultBattleLayout,
  defaultDepositLayout,
  defaultEvolutionLayout,
  defaultMainMapNodePositions,
  defaultMainMapRoads,
  defaultMainMapUiLayout,
  defaultMapGridLayout,
  defaultLuogoLayout,
} from './defaultAdminTheme'

export const adminThemePresets: AdminTheme[] = [
  defaultAdminTheme,
  {
    id: 'arkamon-purple-night',
    name: 'Notte Viola',
    colors: {
      primary: '#c084fc',
      primaryHover: '#e9d5ff',
      bg: '#111827',
      surface: '#24193d',
      surfaceHover: '#3b2860',
      text: '#f8fafc',
      textMuted: '#c4b5fd',
      border: '#7c3aed',
      hpHigh: '#22c55e',
      hpMid: '#facc15',
      hpLow: '#fb7185',
    },
    ui: {
      panelRadius: 18,
      buttonRadius: 14,
      panelOpacity: 0.96,
      shadowIntensity: 1.2,
      buttonScale: 0.94,
      stageScale: 1,
      fontScale: 1,
      mainMapRoadOpacity: 0.42,
    },
    assets: {},
    layouts: {
      battle: defaultBattleLayout,
      mainMapNodes: defaultMainMapNodePositions,
      mainMapRoads: defaultMainMapRoads,
      mainMapUi: defaultMainMapUiLayout,
      mapGrid: defaultMapGridLayout,
      luogo: defaultLuogoLayout,
      deposit: defaultDepositLayout,
      evolution: defaultEvolutionLayout,
    },
  },
  {
    id: 'arkamon-bright-cartoon',
    name: 'Cartoon Luminoso',
    colors: {
      primary: '#f97316',
      primaryHover: '#fdba74',
      bg: '#e0f2fe',
      surface: '#ffffff',
      surfaceHover: '#fef3c7',
      text: '#172554',
      textMuted: '#475569',
      border: '#38bdf8',
      hpHigh: '#16a34a',
      hpMid: '#ca8a04',
      hpLow: '#dc2626',
    },
    ui: {
      panelRadius: 22,
      buttonRadius: 18,
      panelOpacity: 0.98,
      shadowIntensity: 0.65,
      buttonScale: 0.96,
      stageScale: 1,
      fontScale: 1,
      mainMapRoadOpacity: 0.42,
    },
    assets: {
      titleBackground: '/assets/s220308-cartoon-palm-tree-e03-mainpreview-beaece814012dcedf276eb90c00a71ed0e83e25e12b2801c4c825ab8f330bc4e.jpg',
    },
    layouts: {
      battle: defaultBattleLayout,
      mainMapNodes: defaultMainMapNodePositions,
      mainMapRoads: defaultMainMapRoads,
      mainMapUi: defaultMainMapUiLayout,
      mapGrid: defaultMapGridLayout,
      luogo: defaultLuogoLayout,
      deposit: defaultDepositLayout,
      evolution: defaultEvolutionLayout,
    },
  },
  {
    id: 'arkamon-battle-dark',
    name: 'Battaglia Dark',
    colors: {
      primary: '#ef4444',
      primaryHover: '#fca5a5',
      bg: '#020617',
      surface: '#111827',
      surfaceHover: '#1f2937',
      text: '#f9fafb',
      textMuted: '#9ca3af',
      border: '#991b1b',
      hpHigh: '#10b981',
      hpMid: '#f59e0b',
      hpLow: '#ef4444',
    },
    ui: {
      panelRadius: 10,
      buttonRadius: 8,
      panelOpacity: 0.94,
      shadowIntensity: 1.6,
      buttonScale: 0.93,
      stageScale: 1,
      fontScale: 1,
      mainMapRoadOpacity: 0.42,
    },
    assets: {
      battleBackground: '/backgrounds/battle_forest.jpg',
    },
    layouts: {
      battle: defaultBattleLayout,
      mainMapNodes: defaultMainMapNodePositions,
      mainMapRoads: defaultMainMapRoads,
      mainMapUi: defaultMainMapUiLayout,
      mapGrid: defaultMapGridLayout,
      luogo: defaultLuogoLayout,
      deposit: defaultDepositLayout,
      evolution: defaultEvolutionLayout,
    },
  },
  {
    id: 'arkamon-golden-fantasy',
    name: 'Fantasy Dorato',
    colors: {
      primary: '#d97706',
      primaryHover: '#fbbf24',
      bg: '#1c1917',
      surface: '#292524',
      surfaceHover: '#44403c',
      text: '#fff7ed',
      textMuted: '#d6d3d1',
      border: '#a16207',
      hpHigh: '#65a30d',
      hpMid: '#facc15',
      hpLow: '#b91c1c',
    },
    ui: {
      panelRadius: 16,
      buttonRadius: 12,
      panelOpacity: 0.97,
      shadowIntensity: 1.25,
      buttonScale: 0.95,
      stageScale: 1,
      fontScale: 1,
      mainMapRoadOpacity: 0.42,
    },
    assets: {},
    layouts: {
      battle: defaultBattleLayout,
      mainMapNodes: defaultMainMapNodePositions,
      mainMapRoads: defaultMainMapRoads,
      mainMapUi: defaultMainMapUiLayout,
      mapGrid: defaultMapGridLayout,
      luogo: defaultLuogoLayout,
      deposit: defaultDepositLayout,
      evolution: defaultEvolutionLayout,
    },
  },
]
